### ISSUE TITLE
მედიუმის პოსტის (io.js Week of February 6th 2015) გადათარგმნა

### ISSUE THREAD

**Issue by Stichoza** [iojs/iojs-ka#2]
ბმული: [io.js Week of February 6th 2015](https://medium.com/node-js-javascript/io-js-week-of-february-6th-2015-e185388549a4)

**Comment by davit-khaburdzania** [comment]
ვინმემ თუ არ დაიწყო უკვე შემიძლია გადავთარგმნო და მერე შესწორებები შევიტანოთ ერთად.
ჩემი აზრით ჯერჯერობით სჯობს Medium-ზე დავდოთ

**Comment by Stichoza** [comment]
ამ რეპოში რო დავდოთ md ფორმატში მგონი კაი იქნება. ქომითზე კომენტარები და ა.შ ეგ იქნება შესწორებებზე დისკუსია.

**Comment by irakli-janiashvili** [comment]
კი აქ დავდოთ, დავარევიუოთ ყველამ და მერე დავარელიზოთ, რთულია ერთი კაცისთვის ქართული თარგმანი /posts ფოლდერში გავიტანოთ და თარიღებით გავუშვათ

**Comment by Stichoza** [comment]
ლაიქ [ზის ვან](https://github.com/iojs/iojs-ka/blob/master/posts/medium-feb-6.md)

**Comment by davit-khaburdzania** [comment]
დავიწყე მაგრამ აღმოვაჩინე რომ i suck თარგმნაში და პუნკტუაციაში და შევჩერდი ;დ

**Comment by irakli-janiashvili** [comment]
სიცხელე აკლია ნიუსს :fire: მე გავაგრძელებ

**Comment by irakli-janiashvili** [comment]
[გადახედეთ აბა](https://github.com/iojs/iojs-ka/blob/master/posts/medium-feb-6.md)

**Comment by irakli-janiashvili** [comment]
@Stichoza @davit-khaburdzania მეოთხე პუნქტს კარგად გადახედეთ რა რაღაც მგონი არ გამოვიდა კარგად..

**Comment by irakli-janiashvili** [comment]
@nodar-chkuaselidze მგონი კარგია უკვე

+1 მედიუმზე გაშვებას

**Comment by irakli-janiashvili** [comment]
თქვენი არ ვიცი მარა markdown-ში წერა სტატიის ცოტა pain in the ass გამოდგა და პირდაპირ მედიუმზე ვწეროთ ჯობია და დრაფტად შევინახოთ ხოლმე, რას ფიქრობთ?

**Comment by Stichoza** [comment]
რავი მე ძაან მიჩვეული ვარ დაჟე მეილებს ვწერ მარკდაუნში და მაგიტო მქონდა ეგ იდეა :დ კი დრაფტებად ვწეროთ მაშინ.

**Comment by irakli-janiashvili** [comment]
დრაფტი https://medium.com/p/1a2c60598ee3/edit

**Comment by irakli-janiashvili** [comment]
თუ კმაყოფილი ხართ მგონი დროა დავაფაბლიშოთ და დავხუროთ ეს issue

**Comment by davit-khaburdzania** [comment]
@irakli-janiashvili 
1. ემატება ლინუქს თრეისინგი (LTTNG). 
"ლინუქს თრეისინგი" ინგლისურად შეცვალე ზემოთ ინგლისურ ვარიანტს ვიყენებთ

**Comment by davit-khaburdzania** [comment]
არაკონსენსისტურობას ააქვს ადგილი ;დ

**Comment by irakli-janiashvili** [comment]
@davit-khaburdzania dude, შეცვალე შენით მე რომ არ დამთაგო ;დ

**Comment by davit-khaburdzania** [comment]
@irakli-janiashvili okay :grinning:

**Comment by Stichoza** [comment]
ეს თებერვალიც ჩავასწორე ორივეგან და დავაფაბლიშებ, ნუ ვიბურღავთ ტვინს ზედმეტად :D

**Comment by Stichoza** [comment]
https://medium.com/@iojs_ka/io-js-6-2015-1a2c60598ee3

**Comment by davit-khaburdzania** [comment]
nice work guys ძალა ერთობაშია <3 :+1:

**Comment by nodar-chkuaselidze** [comment]
cool (Y)

**Comment by irakli-janiashvili** [comment]
არა ისევ კოლაბორაციულ რეჟიმში ჯობია აქ დავდოთ სტატიები და მერე მედიუმზე წავიღოთ

**Comment by davit-khaburdzania** [comment]
@irakli-janiashvili agreed
